AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer for WordPress
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where ALB will be deployed
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 1 ID
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 2 ID
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group for ALB

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: WordPressALB
      Scheme: internet-facing
      Type: application
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: WordPressTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: "/"
      TargetType: instance

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  ALBURL:
    Description: URL of the Application Load Balancer
    Value: !Join ['', ['http://', !GetAtt ALB.DNSName]]
