AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS EFS File System for WordPress shared storage"

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID where EFS will be deployed"
  
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: "Private Subnet 1 ID for EFS Mount Target"
  
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: "Private Subnet 2 ID for EFS Mount Target"
  
  WordPressSG:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Security Group ID for WordPress instances that need EFS access"

Resources:
  # EFS Security Group
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for EFS allowing NFS access"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !Ref WordPressSG  

  # EFS File System
  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      FileSystemTags:
        - Key: "Name"
          Value: "WordPressEFS"

  # Mount Target for Private Subnet 1
  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref PrivateSubnet1
      SecurityGroups:
        - !Ref EFSSecurityGroup

  # Mount Target for Private Subnet 2
  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref PrivateSubnet2
      SecurityGroups:
        - !Ref EFSSecurityGroup

Outputs:
  EFSFileSystemId:
    Description: "The ID of the EFS file system"
    Value: !Ref EFSFileSystem
  
  EFSDNSName:
    Description: Constructed DNS Name for EFS
    Value: !Sub "${EFSFileSystem}.efs.${AWS::Region}.amazonaws.com"

